import React, { useState } from 'react';
import apiClient from '../../services/api';

export default function WorkerRegistration({ farms }) {
  const [form, setForm] = useState({ fullName: '', phone: '', email: '', farmId: farms[0]?.id || '' });
  const [result, setResult] = useState(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const submit = async (event) => { event.preventDefault(); setBusy(true); setError(''); setResult(null); try { const response = await apiClient.post(`/farms/${form.farmId}/worker-onboarding`, { fullName: form.fullName, phone: form.phone, email: form.email || undefined }); setResult(response.data); setForm({ ...form, fullName: '', phone: '', email: '' }); } catch (requestError) { setError(requestError.message || 'Unable to register worker.'); } finally { setBusy(false); } };
  return <div className="panel worker-registration"><div className="panel-heading"><div><p className="eyebrow">WORKER ONBOARDING</p><h3>Register a new worker</h3><p className="muted">The worker will verify their phone and create a private password during first login.</p></div></div>{!farms.length ? <p className="muted">Create a farm before registering a worker.</p> : <>{error && <div className="notice error" role="alert">{error}</div>}{result ? <div className="worker-credential"><h4>Worker registered successfully</h4><p><strong>{result.worker.firstName} {result.worker.lastName}</strong> can now complete phone verification.</p><label>Temporary password<input value={result.temporaryPassword} readOnly /></label><label>Onboarding link<input value={`${window.location.origin}/worker-onboarding/${result.onboardingToken}`} readOnly /></label><p className="muted">Share these details securely once. The worker must create a new password during onboarding.</p><button className="outline-button" type="button" onClick={() => setResult(null)}>Register another worker</button></div> : <form className="support-form" onSubmit={submit}><label>Worker full name<input value={form.fullName} minLength="3" maxLength="100" onChange={(event) => setForm({ ...form, fullName: event.target.value })} required /></label><label>Phone number<input value={form.phone} placeholder="+233..." autoComplete="tel" onChange={(event) => setForm({ ...form, phone: event.target.value })} required /></label><label>Email address <span className="muted">(optional)</span><input type="email" value={form.email} autoComplete="email" onChange={(event) => setForm({ ...form, email: event.target.value })} /></label><label>Farm<select value={form.farmId} onChange={(event) => setForm({ ...form, farmId: event.target.value })} required>{farms.map((farm) => <option value={farm.id} key={farm.id}>{farm.name}</option>)}</select></label><button className="primary-button" disabled={busy}>{busy ? 'Registering...' : 'Register worker'} <span>+</span></button></form>}</>}</div>;
}
