import React, { useEffect, useState } from 'react';
import apiClient from '../../services/api';

function FeedbackQueue() {
  const [items, setItems] = useState([]); const [selected, setSelected] = useState(null); const [filters, setFilters] = useState({ search: '', status: '' }); const [message, setMessage] = useState(''); const [note, setNote] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  const load = async () => { setLoading(true); setError(''); try { const result = await apiClient.get(`/admin/feedback?${new URLSearchParams(filters)}`); setItems(result.data || []); } catch (requestError) { setError(requestError.message || 'Unable to load feedback.'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [filters.status]);
  const open = async (id) => { setError(''); try { const result = await apiClient.get(`/admin/feedback/${id}`); setSelected(result.data); } catch (requestError) { setError(requestError.message || 'Unable to load feedback details.'); } };
  const patch = async (data) => { try { const result = await apiClient.patch(`/admin/feedback/${selected.id}`, data); setSelected({ ...selected, ...result.data }); await load(); } catch (requestError) { setError(requestError.message || 'Unable to update feedback.'); } };
  const respond = async (event, internal = false) => { event.preventDefault(); const value = internal ? note : message; if (!value.trim()) return; try { const result = await apiClient.post(`/admin/feedback/${selected.id}/${internal ? 'internal-note' : 'respond'}`, internal ? { note: value } : { message: value }); setSelected({ ...selected, ...(internal ? { notes: [...(selected.notes || []), result.data] } : { responses: [...(selected.responses || []), result.data] }) }); internal ? setNote('') : setMessage(''); } catch (requestError) { setError(requestError.message || 'Unable to save response.'); } };
  return <div className="support-admin-grid"><div className="panel"><div className="panel-heading"><div><p className="eyebrow">INBOX</p><h3>Feedback queue</h3></div><span className="record-count">{items.length} shown</span></div><div className="filter-row"><input placeholder="Search feedback" value={filters.search} onChange={(event) => setFilters({ ...filters, search: event.target.value })} onKeyDown={(event) => event.key === 'Enter' && load()} /><select value={filters.status} onChange={(event) => setFilters({ ...filters, status: event.target.value })}><option value="">All statuses</option><option value="NEW">New</option><option value="IN_REVIEW">In review</option><option value="IN_PROGRESS">In progress</option><option value="RESOLVED">Resolved</option><option value="CLOSED">Closed</option></select></div>{error && <div className="notice error" role="alert">{error}</div>}{loading ? <div className="loading-line" aria-label="Loading feedback" /> : items.map((item) => <button className="support-admin-row" type="button" key={item.id} onClick={() => open(item.id)}><span><strong>{item.reference}</strong><small>{item.subject}</small></span><span><b>{item.priority}</b><small>{item.status.replaceAll('_', ' ')}</small></span></button>)}</div>{selected ? <div className="panel support-admin-detail"><div className="panel-heading"><div><p className="eyebrow">{selected.reference}</p><h3>{selected.subject}</h3></div><select value={selected.status} onChange={(event) => patch({ status: event.target.value })}><option value="NEW">New</option><option value="IN_REVIEW">In review</option><option value="IN_PROGRESS">In progress</option><option value="RESOLVED">Resolved</option><option value="CLOSED">Closed</option></select></div><p>{selected.description}</p><small className="muted">Submitted by {selected.user?.firstName} {selected.user?.lastName} on {new Date(selected.createdAt).toLocaleString()}</small><hr /><h4>User-visible responses</h4>{(selected.responses || []).map((response) => <div className="support-note" key={response.id}><p>{response.message}</p><small>{response.author?.firstName} {response.author?.lastName}</small></div>)}<form className="support-inline-form" onSubmit={respond}><textarea value={message} onChange={(event) => setMessage(event.target.value)} placeholder="Write a response to the user" rows="3" /><button className="primary-button">Respond</button></form><h4>Internal notes</h4>{(selected.notes || []).map((entry) => <div className="support-note private" key={entry.id}><p>{entry.note}</p><small>{entry.author?.firstName} {entry.author?.lastName}</small></div>)}<form className="support-inline-form" onSubmit={(event) => respond(event, true)}><textarea value={note} onChange={(event) => setNote(event.target.value)} placeholder="Add an admin-only note" rows="2" /><button className="outline-button">Add note</button></form></div> : <div className="panel support-empty"><p className="muted">Select feedback to view its details.</p></div>}</div>;
}

function FAQAdmin() {
  const [faqs, setFaqs] = useState([]); const [categories, setCategories] = useState([]); const [form, setForm] = useState({ question: '', answer: '', categoryId: '', displayOrder: 0 }); const [error, setError] = useState('');
  const load = async () => { try { const [faqResult, categoryResult] = await Promise.all([apiClient.get('/admin/faqs'), apiClient.get('/admin/faqs/categories')]); setFaqs(faqResult.data || []); setCategories(categoryResult.data || []); if (!form.categoryId && categoryResult.data?.[0]) setForm((current) => ({ ...current, categoryId: categoryResult.data[0].id })); } catch (requestError) { setError(requestError.message || 'Unable to load FAQs.'); } };
  useEffect(() => { load(); }, []);
  const create = async (event) => { event.preventDefault(); try { await apiClient.post('/admin/faqs', form); setForm({ ...form, question: '', answer: '' }); await load(); } catch (requestError) { setError(requestError.message || 'Unable to create FAQ.'); } };
  const publish = async (faq, status) => { try { await apiClient.post(`/admin/faqs/${faq.id}/status`, { status }); await load(); } catch (requestError) { setError(requestError.message || 'Unable to update FAQ.'); } };
  return <div className="support-admin-grid"><div className="panel"><div className="panel-heading"><div><p className="eyebrow">CONTENT</p><h3>FAQ management</h3></div></div>{error && <div className="notice error">{error}</div>}<form className="support-form" onSubmit={create}><label>Question<input value={form.question} onChange={(event) => setForm({ ...form, question: event.target.value })} required /></label><label>Category<select value={form.categoryId} onChange={(event) => setForm({ ...form, categoryId: event.target.value })} required>{categories.map((category) => <option value={category.id} key={category.id}>{category.name}</option>)}</select></label><label>Answer<textarea rows="4" value={form.answer} onChange={(event) => setForm({ ...form, answer: event.target.value })} required /></label><button className="primary-button">Create FAQ</button></form></div><div className="panel">{faqs.map((faq) => <div className="support-admin-row" key={faq.id}><span><strong>{faq.question}</strong><small>{faq.category?.name} · {faq.status}</small></span><button className="text-button" type="button" onClick={() => publish(faq, faq.status === 'PUBLISHED' ? 'DRAFT' : 'PUBLISHED')}>{faq.status === 'PUBLISHED' ? 'Unpublish' : 'Publish'}</button></div>)}</div></div>;
}

export default function AdminSupport() {
  const [tab, setTab] = useState('feedback');
  return <section><div className="section-heading"><div><p className="eyebrow">ADMINISTRATION</p><h2>FAQ & feedback</h2><p className="muted">Keep help content useful and close the loop with users.</p></div></div><div className="support-tabs"><button className={tab === 'feedback' ? 'active' : ''} type="button" onClick={() => setTab('feedback')}>Feedback</button><button className={tab === 'faq' ? 'active' : ''} type="button" onClick={() => setTab('faq')}>FAQs</button></div>{tab === 'feedback' ? <FeedbackQueue /> : <FAQAdmin />}</section>;
}